version: "3"

services:
  apache2-multiphp:
    build:
      context: ./bin/apache2_multiphp
      dockerfile: Dockerfile
    container_name: apache2-multiphp
    #restart: always
    ports:
      - "8022:22"
      - "8080:80"
      - "8443:443"
    links:
      - mariadb-10.4.12
    volumes:
      - ./config/.root_history:/root/.bash_history # file should exist before mounting
      - ./config/.www_history:/home/www/.bash_history # file should exist before mounting
      - ./config/.zsh_history:/home/www/.zsh_history # file should exist before mounting
      - "../:/var/www/html:delegated"
      - ./config/php-8.0/php-apache.ini:/etc/php/8.0/apache2/php.ini
      - ./config/php-8.0/php-cli.ini:/etc/php/8.0/cli/php.ini
      - ./config/php-8.0/php-fpm.ini:/etc/php/8.0/fpm/php.ini
      - ./config/php-7.4/php-apache.ini:/etc/php/7.4/apache2/php.ini
      - ./config/php-7.4/php-cli.ini:/etc/php/7.4/cli/php.ini
      - ./config/php-7.4/php-fpm.ini:/etc/php/7.4/fpm/php.ini
      - ./config/php-7.2/php-apache.ini:/etc/php/7.2/apache2/php.ini
      - ./config/php-7.2/php-cli.ini:/etc/php/7.2/cli/php.ini
      - ./config/php-7.2/php-fpm.ini:/etc/php/7.2/fpm/php.ini
      - ./config/php-5.6/php-apache.ini:/etc/php/5.6/apache2/php.ini
      - ./config/php-5.6/php-cli.ini:/etc/php/5.6/cli/php.ini
      - ./config/php-5.6/php-fpm.ini:/etc/php/5.6/fpm/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./config/hosts:/etc/hosts
      - ./logs/apache2:/var/log/apache2
      - ./logs/php:/var/log/php

  mariadb-10.4.12:
    build:
      context: "./bin/mariadb_10.4.12-bionic"
      dockerfile: Dockerfile
    container_name: mariadb-10.4.12
    #restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config/mysql/docker.cnf:/etc/mysql/mariadb.conf.d/docker.cnf
      - ./logs/mysql:/var/log/mysql
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: www
